name: music_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  assets_audio_player: ^3.1.1
  flutter:
    sdk: flutter
  go_router: ^14.2.2
  marquee_text: ^2.5.0+1
  
  responsive_builder: ^0.7.1
  mini_music_visualizer: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter_gen:
  colors:
    inputs:
      - assets/colors/color_pallet.xml

flutter:
  uses-material-design: true

  
